from .set_temperature import handle_set_temperature
from .set_frequency_penalty import handle_set_frequency_penalty
from .set_presence_penalty import handle_set_presence_penalty
from .change_default_personality import handle_change_default_personality
from .del_config import handle_del_config
from .memory_switch import handle_enable_memory, handle_disable_memory
from .set_time_zone import handle_set_time_zone